# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZJNetwork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

    pod 'AFNetworking'

  # Pods for ZJNetwork

  target 'ZJNetworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZJNetworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
